//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdobePDFServicesFront.Properties
{


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdobePDFServicesFront.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   .docx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionDOCX {
            get {
                return ResourceManager.GetString("ExtensionDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .pdf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionPDF {
            get {
                return ResourceManager.GetString("ExtensionPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .pptx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionPPTX {
            get {
                return ResourceManager.GetString("ExtensionPPTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionXLSX {
            get {
                return ResourceManager.GetString("ExtensionXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionZIP {
            get {
                return ResourceManager.GetString("ExtensionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .\temp\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TempPath {
            get {
                return ResourceManager.GetString("TempPath", resourceCulture);
            }
        }
    }
}
